# GENERATED by rebuild2.py - canonical J1 pinout, single source of truth.
# Row assignment follows the flash's two ball clusters; within a row, pins are
# ordered by ball x so the B.Cu escape carries the horizontal travel.
DF40 = {
   1:'IO4',  2:'GND',  3:'GND',  4:'IO7',  5:'IO3',  6:'GND',  7:'GND',  8:'IO5',
   9:'IO2', 10:'VCC', 11:'GND', 12:'IO8', 13:'IO1', 14:'VCC', 15:'GND', 16:'IO6',
  17:'CLE', 18:'GND', 19:'GND', 20:'RY//BY', 21:'/RE', 22:'GND', 23:'GND', 24:'/WE',
  25:'ALE', 26:'GND', 27:'GND', 28:'/CE', 29:'/WP', 30:'GND',
}
def check():
    odd=[p for p in range(1,31,2)]; even=[p for p in range(2,31,2)]
    sig=lambda n: n not in ('GND','VCC')
    for rowname,pins in (('odd',odd),('even',even)):
        seq=[DF40[p] for p in pins]
        for i,v in enumerate(seq):
            if sig(v):
                for j in (i-1,i+1):
                    if 0<=j<len(seq) and sig(seq[j]):
                        raise AssertionError(f"{rowname}: {v} adjacent to signal {seq[j]}")
    for p in range(1,31,2):
        a,b=DF40[p],DF40[p+1]
        if sig(a) and sig(b): raise AssertionError(f"pins {p}/{p+1}: {a} opposite {b}")
    nets=[v for v in DF40.values() if sig(v)]
    assert sorted(nets)==sorted(['IO%d'%i for i in range(1,9)]+['/CE','/RE','/WE','/WP','CLE','ALE','RY//BY']), nets
    assert list(DF40.values()).count('VCC')==2
    return True
if __name__=='__main__':
    check()
    print("checkerboard OK: no signal adjacent to or opposite another signal")
    print(f"  odd  row: {[(p,DF40[p]) for p in range(1,31,2)]}")
    print(f"  even row: {[(p,DF40[p]) for p in range(2,31,2)]}")
    print(f"  GND x{list(DF40.values()).count('GND')}  VCC x2  signals x15")
